models:
  - name: dim_employer
    description: "Information about the employer such as name, workplace address, organisation number, ..."  
    columns:
      - name: employer_id
        description: "Primary key, a surrgoate key generated based on columns: id, employer_name."
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        data_tests:
          - not_null

        # TODO: add more tests ...

  - name: dim_job_details
    description: "Details about the job ad"     
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - unique
      - name: headline
        data_tests:
          - not_null

        # TODO: add more tests ...

  - name: fct_job_ads
    description: "The facts are relevance and vacancies."
    columns:
      - name: job_details_key    # 外键关系
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
      - name: relevance
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: vacancies
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
            

          
   # TODO: more tests ...




# dbt 的 YAML 配置文件，用于定义 数据模型（models）及其 数据质量测试（data tests），确保数据质量的规则
# 两个维度表：取他们各自的两列并对其两列设置 唯一性和 完整性的测试。
# 一个事实表：vacancies 列： 
# 99% 的数据 (quantile: .99) 必须在 1 到 20 之间，防止极端异常值。
# 最大值必须在 1 到 20 之间，但如果超出范围 仅警告（severity: warn），不会报错
# YAML 不允许 在 key-value 之间 插入注释，必须放在单独一行或者键值对后面 ，就是：的地方不能写




